# LocalActionDiagrams, single 2
#
# DO NOT EDIT THIS FILE - EDIT EXAMPLES IN THE SOURCE INSTEAD!
#
# This file has been generated by AutoDoc. It contains examples extracted from
# the package documentation. Each example is preceded by a comment which gives
# the name of a GAPDoc XML file and a line range from which the example were
# taken. Note that the XML file in turn may have been generated by AutoDoc
# from some other input.
#
gap> START_TEST("localactiondiagrams02.tst");

# doc/_Chapter_RSGraphs.xml:120-136
gap> adj_mat := [[1, 2], [2, 0]];;
gap> rev_map := (2, 4)(3,5);;
gap> vertex_ids := [2, 3];;
gap> graph := RSGraphByAdjacencyMatrix(adj_mat, rev_map, vertex_ids);
<RSGraph with 2 vertices and 5 arcs>
gap> Print(graph);
Vertices = { 2, 3 }
Arcs = {
	1 = ( origin = 2, terminus = 2, inverse = 1 )
	2 = ( origin = 2, terminus = 3, inverse = 4 )
	3 = ( origin = 2, terminus = 3, inverse = 5 )
	4 = ( origin = 3, terminus = 2, inverse = 2 )
	5 = ( origin = 3, terminus = 2, inverse = 3 )
}
Reverse Map = (2,4)(3,5)

#
gap> STOP_TEST("localactiondiagrams02.tst", 1);
