# LocalActionDiagrams, single 10
#
# DO NOT EDIT THIS FILE - EDIT EXAMPLES IN THE SOURCE INSTEAD!
#
# This file has been generated by AutoDoc. It contains examples extracted from
# the package documentation. Each example is preceded by a comment which gives
# the name of a GAPDoc XML file and a line range from which the example were
# taken. Note that the XML file in turn may have been generated by AutoDoc
# from some other input.
#
gap> START_TEST("localactiondiagrams10.tst");

# doc/_Chapter_Local_Action_Diagrams.xml:104-130
gap> graph := RSGraphByAdjacencyList([[1, 1], [1, 2], [2, 1]], (2,3));;
gap> label_1 := Group((1,2));;
gap> SetPermGroupDomain(label_1, [1, 2, 3]);;
gap> label_2 := Group((1,2,3));;
gap> vertex_labels := [label_1, label_2];;
gap> arc_labels := [[1, 2], [3], [1,2,3]];;
gap> lad := LocalActionDiagramFromData(graph, vertex_labels, arc_labels);
<LocalActionDiagram with 2 vertices and 3 arcs>
gap> Print(lad);
Vertices = { 1, 2 }
Arcs = {
	1 = ( origin = 1, terminus = 1, inverse = 1 )
	2 = ( origin = 1, terminus = 2, inverse = 3 )
	3 = ( origin = 2, terminus = 1, inverse = 2 )
}
Reverse Map = (2,3)
Vertex Labels = {
	1 = Group( [ (1,2) ] )
	2 = Group( [ (1,2,3) ] )
}
Arc Labels = {
	1 = [ 1, 2 ]
	2 = [ 3 ]
	3 = [ 1, 2, 3 ]
}

#
gap> STOP_TEST("localactiondiagrams10.tst", 1);
