# LocalActionDiagrams, single 20
#
# DO NOT EDIT THIS FILE - EDIT EXAMPLES IN THE SOURCE INSTEAD!
#
# This file has been generated by AutoDoc. It contains examples extracted from
# the package documentation. Each example is preceded by a comment which gives
# the name of a GAPDoc XML file and a line range from which the example were
# taken. Note that the XML file in turn may have been generated by AutoDoc
# from some other input.
#
gap> START_TEST("localactiondiagrams20.tst");

# doc/_Chapter_Iso.xml:83-90
gap> graph := RSGraphByAdjacencyList([[1, 1], [1, 1], [1, 2], [2, 1], [2, 2], [2, 2]], (3,4));;
gap> aut_group := AutomorphismGroup(graph);;
gap> arc_aut := Elements(aut_group)[5];
(1,5)(2,6)(3,4)
gap> vert_aut := RSGraphVertexAutomorphism(graph, arc_aut);
(1,2)

#
gap> STOP_TEST("localactiondiagrams20.tst", 1);
