# LocalActionDiagrams, single 22
#
# DO NOT EDIT THIS FILE - EDIT EXAMPLES IN THE SOURCE INSTEAD!
#
# This file has been generated by AutoDoc. It contains examples extracted from
# the package documentation. Each example is preceded by a comment which gives
# the name of a GAPDoc XML file and a line range from which the example were
# taken. Note that the XML file in turn may have been generated by AutoDoc
# from some other input.
#
gap> START_TEST("localactiondiagrams22.tst");

# doc/_Chapter_Iso.xml:132-144
gap> graph_1 := RSGraphByAdjacencyList([[1, 1], [1, 1], [1, 1]], ());;
gap> graph_2 := RSGraphByAdjacencyList([[1, 1], [1, 1], [1, 1]], ());;
gap> for iso in RSGraphsIsomorphismsIterator(graph_1, graph_2) do 
>    	Print(iso, "\n"); 
>    od;
[ (), () ]
[ (), (2,3) ]
[ (), (1,3,2) ]
[ (), (1,3) ]
[ (), (1,2,3) ]
[ (), (1,2) ]

#
gap> STOP_TEST("localactiondiagrams22.tst", 1);
