# LocalActionDiagrams, single 26
#
# DO NOT EDIT THIS FILE - EDIT EXAMPLES IN THE SOURCE INSTEAD!
#
# This file has been generated by AutoDoc. It contains examples extracted from
# the package documentation. Each example is preceded by a comment which gives
# the name of a GAPDoc XML file and a line range from which the example were
# taken. Note that the XML file in turn may have been generated by AutoDoc
# from some other input.
#
gap> START_TEST("localactiondiagrams26.tst");

# doc/_Chapter_Enumeration.xml:74-82
gap> lad_list := LocalActionDiagramFromLibrary(3, 2);;
gap> lad := lad_list[4];
<LocalActionDiagram with 2 vertices and 4 arcs>
gap> lad_2 := LocalActionDiagramFromLibrary(3, 2, 4);;
gap> IsomorphismLocalActionDiagrams(lad, lad_2);
[ (), (), rec( 1 := <mapping: Domain([ 1, 2, 3 ]) -> Domain([ 1, 2, 3 ]) >, 
      2 := <mapping: Domain([ 4, 5, 6 ]) -> Domain([ 4, 5, 6 ]) > ) ]

#
gap> STOP_TEST("localactiondiagrams26.tst", 1);
