# LocalActionDiagrams, single 14
#
# DO NOT EDIT THIS FILE - EDIT EXAMPLES IN THE SOURCE INSTEAD!
#
# This file has been generated by AutoDoc. It contains examples extracted from
# the package documentation. Each example is preceded by a comment which gives
# the name of a GAPDoc XML file and a line range from which the example were
# taken. Note that the XML file in turn may have been generated by AutoDoc
# from some other input.
#
gap> START_TEST("localactiondiagrams14.tst");

# doc/_Chapter_Local_Action_Diagrams.xml:399-408
gap> graph := RSGraphByAdjacencyList ([[1, 2], [2, 1]], (1,2));;
gap> group := Group(());;
gap> SetPermGroupDomain(group, [1]);;
gap> vertex_labels := [group, group];;
gap> arc_labels := [[1], [1]];;
gap> lad := LocalActionDiagramFromData(graph, vertex_labels, arc_labels);;
gap> LocalActionDiagramGroupType(lad);
"General"

#
gap> STOP_TEST("localactiondiagrams14.tst", 1);
