# LocalActionDiagrams, single 12
#
# DO NOT EDIT THIS FILE - EDIT EXAMPLES IN THE SOURCE INSTEAD!
#
# This file has been generated by AutoDoc. It contains examples extracted from
# the package documentation. Each example is preceded by a comment which gives
# the name of a GAPDoc XML file and a line range from which the example were
# taken. Note that the XML file in turn may have been generated by AutoDoc
# from some other input.
#
gap> START_TEST("localactiondiagrams12.tst");

# doc/_Chapter_Local_Action_Diagrams.xml:334-346
gap> graph := RSGraphByAdjacencyList([[1, 2], [2, 1]], (1,2));;
gap> vertex_labels := [SymmetricGroup(3), Group((1,2,3))];;
gap> arc_labels := [[1,2,3], [1,2,3]];;
gap> lad := LocalActionDiagramFromData(graph, vertex_labels, arc_labels);;
gap> LocalActionDiagramRegularTree(lad);
3
gap> vertex_labels_2 := [SymmetricGroup(3), Group((1,2))];;
gap> arc_labels_2 := [[1,2,3], [1,2]];;
gap> lad_2 := LocalActionDiagramFromData(graph, vertex_labels_2, arc_labels_2);;
gap> LocalActionDiagramRegularTree(lad_2);
fail

#
gap> STOP_TEST("localactiondiagrams12.tst", 1);
