# LocalActionDiagrams, single 17
#
# DO NOT EDIT THIS FILE - EDIT EXAMPLES IN THE SOURCE INSTEAD!
#
# This file has been generated by AutoDoc. It contains examples extracted from
# the package documentation. Each example is preceded by a comment which gives
# the name of a GAPDoc XML file and a line range from which the example were
# taken. Note that the XML file in turn may have been generated by AutoDoc
# from some other input.
#
gap> START_TEST("localactiondiagrams17.tst");

# doc/_Chapter_IO_Operations_and_Visualisation.xml:82-91
gap> graph := RSGraphByAdjacencyList([[1, 1]], ());;
gap> RSGraphToWritableString(graph);
"1|1,1,1|P"
gap> lad := LocalActionDiagramFromData(graph, [Group((1,2))], [[1,2]]);;
gap> LocalActionDiagramGroupType(lad);;
gap> LocalActionDiagramToWritableString(lad);
"1|1,1,1|P/1:P2,1:1,2|1:1,2|LocalActionDiagramGroupType!General|LocalActionDia\
gramScopos! "

#
gap> STOP_TEST("localactiondiagrams17.tst", 1);
