# LocalActionDiagrams, single 1
#
# DO NOT EDIT THIS FILE - EDIT EXAMPLES IN THE SOURCE INSTEAD!
#
# This file has been generated by AutoDoc. It contains examples extracted from
# the package documentation. Each example is preceded by a comment which gives
# the name of a GAPDoc XML file and a line range from which the example were
# taken. Note that the XML file in turn may have been generated by AutoDoc
# from some other input.
#
gap> START_TEST("localactiondiagrams01.tst");

# doc/_Chapter_RSGraphs.xml:73-83
gap> adj_list := [[1, 2], [2, 1], [2, 2], [2, 2], [1, 1]];;
gap> rev_map := (1,2)(3,4);;
gap> graph := RSGraphByAdjacencyList(adj_list, rev_map);
<RSGraph with 2 vertices and 5 arcs>
gap> adj_list2 := [[2, 2]];;
gap> rev_map2 := ();;
gap> vertex_ids := [2];;
gap> graph := RSGraphByAdjacencyList(adj_list2, rev_map2, vertex_ids);
<RSGraph with 1 vertex and 1 arc>

#
gap> STOP_TEST("localactiondiagrams01.tst", 1);
