# LocalActionDiagrams, single 25
#
# DO NOT EDIT THIS FILE - EDIT EXAMPLES IN THE SOURCE INSTEAD!
#
# This file has been generated by AutoDoc. It contains examples extracted from
# the package documentation. Each example is preceded by a comment which gives
# the name of a GAPDoc XML file and a line range from which the example were
# taken. Note that the XML file in turn may have been generated by AutoDoc
# from some other input.
#
gap> START_TEST("localactiondiagrams25.tst");

# doc/_Chapter_Enumeration.xml:43-50
gap> graph_list := RSGraphFromLibrary(3, 2);;
gap> graph := graph_list[4];
<RSGraph with 2 vertices and 3 arcs>
gap> graph_2 := RSGraphFromLibrary(3, 2, 4);;
gap> IsomorphismRSGraphs(graph, graph_2);
()

#
gap> STOP_TEST("localactiondiagrams25.tst", 1);
