# LocalActionDiagrams, single 17
#
# DO NOT EDIT THIS FILE - EDIT EXAMPLES IN THE SOURCE INSTEAD!
#
# This file has been generated by AutoDoc. It contains examples extracted from
# the package documentation. Each example is preceded by a comment which gives
# the name of a GAPDoc XML file and a line range from which the example were
# taken. Note that the XML file in turn may have been generated by AutoDoc
# from some other input.
#
gap> START_TEST("localactiondiagrams17.tst");

# doc/_Chapter_Local_Action_Diagrams.xml:471-486
gap> adj_list := [[1, 2], [2, 1], [2, 3], [3, 2], [3, 1], [1, 3], [1, 1]];;
gap> graph := RSGraphByAdjacencyList(adj_list, (1,2)(3,4)(5,6));;
gap> vertex_labels := [];;
gap> Add(vertex_labels, Group((1, 2, 3), (4,5), (6,7)));;
gap> Add(vertex_labels, Group((1, 2), (3, 4, 5)));;
gap> Add(vertex_labels, Group((1, 2), (3, 4)));;
gap> arc_labels := [[1, 2, 3], [3, 4, 5], [1, 2], [1, 2], [3,4], [4,5], [6,7]];;
gap> lad := LocalActionDiagramFromData(graph, vertex_labels, arc_labels);;
gap> LocalActionDiagramIsDiscrete(lad);
false
gap> LocalActionDiagramIsUniscalar(lad);
false
gap> LocalActionDiagramIsUnimodular(lad);
true

#
gap> STOP_TEST("localactiondiagrams17.tst", 1);
