# LocalActionDiagrams, single 3
#
# DO NOT EDIT THIS FILE - EDIT EXAMPLES IN THE SOURCE INSTEAD!
#
# This file has been generated by AutoDoc. It contains examples extracted from
# the package documentation. Each example is preceded by a comment which gives
# the name of a GAPDoc XML file and a line range from which the example were
# taken. Note that the XML file in turn may have been generated by AutoDoc
# from some other input.
#
gap> START_TEST("localactiondiagrams03.tst");

# doc/_Chapter_RSGraphs.xml:176-183
gap> adj_list := [[1, 2], [2, 1], [2, 2], [2, 2], [1, 1]];;
gap> rev_map := (1,2)(3,4);;
gap> graph := RSGraphByAdjacencyList(adj_list, rev_map);
<RSGraph with 2 vertices and 5 arcs>
gap> RSGraphArcs(graph).1;
rec( inverse := 2, origin := 1, terminus := 2 )

#
gap> STOP_TEST("localactiondiagrams03.tst", 1);
