# LocalActionDiagrams, single 7
#
# DO NOT EDIT THIS FILE - EDIT EXAMPLES IN THE SOURCE INSTEAD!
#
# This file has been generated by AutoDoc. It contains examples extracted from
# the package documentation. Each example is preceded by a comment which gives
# the name of a GAPDoc XML file and a line range from which the example were
# taken. Note that the XML file in turn may have been generated by AutoDoc
# from some other input.
#
gap> START_TEST("localactiondiagrams07.tst");

# doc/_Chapter_RSGraphs.xml:416-440
gap> adj_list := [[1, 2], [2, 1], [1, 2], [2, 1], [2, 2]];;
gap> rev_map := (1,2)(3,4);;
gap> graph := RSGraphByAdjacencyList(adj_list, rev_map);;
gap> Print(graph);
Vertices = { 1, 2 }
Arcs = {
	1 = ( origin = 1, terminus = 2, inverse = 2 )
	2 = ( origin = 2, terminus = 1, inverse = 1 )
	3 = ( origin = 1, terminus = 2, inverse = 4 )
	4 = ( origin = 2, terminus = 1, inverse = 3 )
	5 = ( origin = 2, terminus = 2, inverse = 5 )
}
Reverse Map = (1,2)(3,4)
gap> subgraph := RSGraphSubgraph(graph, [1,2,5]);
<RSGraph with 2 vertices and 3 arcs>
gap> Print(subgraph);
Vertices = { 1, 2 }
Arcs = {
	1 = ( origin = 1, terminus = 2, inverse = 2 )
	2 = ( origin = 2, terminus = 1, inverse = 1 )
	5 = ( origin = 2, terminus = 2, inverse = 5 )
}
Reverse Map = (1,2)(3,4)

#
gap> STOP_TEST("localactiondiagrams07.tst", 1);
