# LocalActionDiagrams, single 24
#
# DO NOT EDIT THIS FILE - EDIT EXAMPLES IN THE SOURCE INSTEAD!
#
# This file has been generated by AutoDoc. It contains examples extracted from
# the package documentation. Each example is preceded by a comment which gives
# the name of a GAPDoc XML file and a line range from which the example were
# taken. Note that the XML file in turn may have been generated by AutoDoc
# from some other input.
#
gap> START_TEST("localactiondiagrams24.tst");

# doc/_Chapter_Iso.xml:229-242
gap> graph := RSGraphByAdjacencyList([[1, 2], [2, 1]], (1,2));;
gap> lad_1 := LocalActionDiagramFromData(graph, [Group((1,2)), Group((3,4))], \
>                                        [[1, 2], [3, 4]]);;
gap> lad_2 := LocalActionDiagramFromData(graph, [Group((3,4)), Group((1,2))], \
>                                        [[3, 4], [1, 2]]);;
gap> iso := IsomorphismLocalActionDiagrams(lad_1, lad_2);;
gap> for elm in iso do Print(elm, "\n"); od;
()
()
rec(
  1 := <mapping: Domain([ 1, 2 ]) -> Domain([ 3, 4 ]) >,
  2 := <mapping: Domain([ 3, 4 ]) -> Domain([ 1, 2 ]) > )

#
gap> STOP_TEST("localactiondiagrams24.tst", 1);
