# LocalActionDiagrams, single 27
#
# DO NOT EDIT THIS FILE - EDIT EXAMPLES IN THE SOURCE INSTEAD!
#
# This file has been generated by AutoDoc. It contains examples extracted from
# the package documentation. Each example is preceded by a comment which gives
# the name of a GAPDoc XML file and a line range from which the example were
# taken. Note that the XML file in turn may have been generated by AutoDoc
# from some other input.
#
gap> START_TEST("localactiondiagrams27.tst");

# doc/_Chapter_Enumeration.xml:99-105
gap> lad_list := LocalActionDiagramFromLibrary(3, 3);;
gap> Size(lad_list);
78
gap> NumberLocalActionDiagrams(3, 3);
78

#
gap> STOP_TEST("localactiondiagrams27.tst", 1);
