# LocalActionDiagrams, single 18
#
# DO NOT EDIT THIS FILE - EDIT EXAMPLES IN THE SOURCE INSTEAD!
#
# This file has been generated by AutoDoc. It contains examples extracted from
# the package documentation. Each example is preceded by a comment which gives
# the name of a GAPDoc XML file and a line range from which the example were
# taken. Note that the XML file in turn may have been generated by AutoDoc
# from some other input.
#
gap> START_TEST("localactiondiagrams18.tst");

# doc/_Chapter_Iso.xml:39-43
gap> graph := RSGraphByAdjacencyList([[1, 1], [1, 1], [1, 1]], (2,3));;
gap> AutomorphismGroup(graph);
Group([ (2,3) ])

#
gap> STOP_TEST("localactiondiagrams18.tst", 1);
