# LocalActionDiagrams, single 6
#
# DO NOT EDIT THIS FILE - EDIT EXAMPLES IN THE SOURCE INSTEAD!
#
# This file has been generated by AutoDoc. It contains examples extracted from
# the package documentation. Each example is preceded by a comment which gives
# the name of a GAPDoc XML file and a line range from which the example were
# taken. Note that the XML file in turn may have been generated by AutoDoc
# from some other input.
#
gap> START_TEST("localactiondiagrams06.tst");

# doc/_Chapter_RSGraphs.xml:381-392
gap> adj_list := [[1, 2], [2, 1], [2, 2]];;
gap> rev_map := (1,2);;
gap> graph := RSGraphByAdjacencyList(adj_list, rev_map);;
gap> for arc in RSGraphArcIterator(graph) do
>     View(arc);
>     Print("\n");
> od;
[ 1, rec( inverse := 2, origin := 1, terminus := 2 ) ]
[ 2, rec( inverse := 1, origin := 2, terminus := 1 ) ]
[ 3, rec( inverse := 3, origin := 2, terminus := 2 ) ]

#
gap> STOP_TEST("localactiondiagrams06.tst", 1);
