# LocalActionDiagrams, single 4
#
# DO NOT EDIT THIS FILE - EDIT EXAMPLES IN THE SOURCE INSTEAD!
#
# This file has been generated by AutoDoc. It contains examples extracted from
# the package documentation. Each example is preceded by a comment which gives
# the name of a GAPDoc XML file and a line range from which the example were
# taken. Note that the XML file in turn may have been generated by AutoDoc
# from some other input.
#
gap> START_TEST("localactiondiagrams04.tst");

# doc/_Chapter_RSGraphs.xml:271-284
gap> adj_list := [[1, 2], [2, 1], [2, 2], [2, 2]];;
gap> rev_map := (1,2)(3,4);;
gap> graph := RSGraphByAdjacencyList(adj_list, rev_map);
<RSGraph with 2 vertices and 4 arcs>
gap> RSGraphOutNeighbours(graph);
rec( 1 := [ 2 ], 2 := [ 1, 2 ] )
gap> RSGraphInNeighbours(graph);
rec( 1 := [ 2 ], 2 := [ 1, 2 ] )
gap> RSGraphOutArcs(graph);
rec( 1 := [ 1 ], 2 := [ 2, 3, 4 ] )
gap> RSGraphInArcs(graph);
rec( 1 := [ 2 ], 2 := [ 1, 3, 4 ] )

#
gap> STOP_TEST("localactiondiagrams04.tst", 1);
