# LocalActionDiagrams, single 8
#
# DO NOT EDIT THIS FILE - EDIT EXAMPLES IN THE SOURCE INSTEAD!
#
# This file has been generated by AutoDoc. It contains examples extracted from
# the package documentation. Each example is preceded by a comment which gives
# the name of a GAPDoc XML file and a line range from which the example were
# taken. Note that the XML file in turn may have been generated by AutoDoc
# from some other input.
#
gap> START_TEST("localactiondiagrams08.tst");

# doc/_Chapter_RSGraphs.xml:527-556
gap> adj_list := [[1, 2], [2, 1], [1, 3], [3, 1], [1, 4], [4, 1], \
>                 [2, 3], [3, 2], [3, 4], [4, 3]];;
gap> rev_map := (1,2)(3,4)(5,6)(7,8)(9,10);;
gap> graph := RSGraphByAdjacencyList(adj_list, rev_map);;
gap> tree_bfs := RSGraphSpanningTree(graph);;
gap> Print(tree_bfs);
Vertices = { 1, 2, 3, 4 }
Arcs = {
	1 = ( origin = 1, terminus = 2, inverse = 2 )
	2 = ( origin = 2, terminus = 1, inverse = 1 )
	3 = ( origin = 1, terminus = 3, inverse = 4 )
	4 = ( origin = 3, terminus = 1, inverse = 3 )
	5 = ( origin = 1, terminus = 4, inverse = 6 )
	6 = ( origin = 4, terminus = 1, inverse = 5 )
}
Reverse Map = (1,2)(3,4)(5,6)(7,8)(9,10)
gap> tree_dfs := RSGraphSpanningTree(graph, "dfs");;
gap> Print(tree_dfs);
Vertices = { 1, 2, 3, 4 }
Arcs = {
	1 = ( origin = 1, terminus = 2, inverse = 2 )
	2 = ( origin = 2, terminus = 1, inverse = 1 )
	7 = ( origin = 2, terminus = 3, inverse = 8 )
	8 = ( origin = 3, terminus = 2, inverse = 7 )
	9 = ( origin = 3, terminus = 4, inverse = 10 )
	10 = ( origin = 4, terminus = 3, inverse = 9 )
}
Reverse Map = (1,2)(3,4)(5,6)(7,8)(9,10)

#
gap> STOP_TEST("localactiondiagrams08.tst", 1);
